export const GET_BRANCHES = "GET_BRANCHES";
export const POST_BRANCH = "POST_BRANCH";
export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const DELETE_BRANCH = "DELETE_BRANCH";

export const GET_COUNTRIES = "GET_COUNTRIES";
export const POST_COUNTRY = "POST_COUNTRY";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";

export const AUTH_USER = "AUTH_USER";
